# Using lightweight alpine image
FROM ubuntu:20.04
RUN apt update && apt install -y python3 python3-pip

# Defining working directory and Installing packages
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt && pip3 install cryptography

# adding source code
COPY app.py ./


# Start app
EXPOSE 5000
ENTRYPOINT ["flask", "run"]